version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: food_express_delivery
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=${PGDATA}

    ports:  
      - "5432:5432"
    volumes:
      - ${HOST_VOLUME_PATH}:${POSTGRES_VOLUME_PATH}:rw  