name: delivery_project_using_clean_code
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  bcrypt: ^1.1.3
  crypto: ^3.0.3
  dart_jsonwebtoken: ^2.12.1
  dotenv: ^4.2.0
  postgresql2: ^1.5.1
  shelf: ^1.4.1
  shelf_modular: ^2.1.0
  uuid: ^4.2.1
  path: ^1.8.0
  http: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  mocktail: ^1.0.1
  test: ^1.21.0
